### PR TITLE
Rebranding calamares

### PR DESCRIPTION
**Pull request by artemtech**
beberapa catatan:
- perlu memaketkan calamares-settings-blankon ke repo arsip/arsip-dev. sumber kode ada di https://github.com/artemtech/calamares-settings-blankon
- perlu memaketkan grub untuk versi signed grub-efi nya

goal PR ini:
- calamares bisa autostart saat booting
- bisa menikmati calamares rasa blankon :)

### CODE REVIEW

**Comment by herpiko** [comment]
Some notes:
- There is no guarantee that the builder machine is having docker installed
- We should package the calamares to our dev repo instead of injecting the binary like this here.

**Review by herpiko — CHANGES_REQUESTED** [review]
Wait for this https://github.com/BlankOn/Verbeek/issues/168 then drop the docker and deb stuff.

**Comment by antosamalona** [comment]
Error 
https://pastebin.com/HiPHbmqu

**Comment by antosamalona** [comment]
Error
https://pastebin.com/HiPHbmqu

**Pull request merged**
